### PR TITLE
Add dotnet 8 support

### PR DESCRIPTION
**Pull request by SandGrainOne**
## Description
Adding dotnet 8 support.

## Related Issue(s)
- #74 

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [x] Manual testing done (required)
- [x] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [x] All tests run green

### CODE REVIEW

**Comment by ivarne** [comment]
This is more a «drop net6.0 support» than a «add net8.0 support», but that is likely a good thing.

Only downside I can see is that if we get a security issue, we’d need to release a fixed version for net6.0 also, as many apps still uses it.

**Comment by SandGrainOne** [comment]
If I'm missing something I'd like to know. I haven't done any thorough testing, but I get both Events and Profile to start. Those are dotnet 7 and 8 respectively.

**Comment by ivarne** [comment]
I'm pretty sure I have had issues referencing a library that only targets net8.0 from a project that targets a lower version. How did you test? You have presumably not published this version to NuGet? Did you somehow use a way to override the compatibility check locally, or just not noticed that an older version of the library was used?

**Comment by SandGrainOne** [comment]
1. I added a new NuGet package source from a local folder.
2. I opened the package as a zip file and ensured that there is both a net6 and net8 folders with their own dll.
3. When building the application, all libraries are copied to the bin folder. I looked at the file properties and ensured it's the version I made.

**Comment by SandGrainOne** [comment]
I did add a `<TargetFrameworks>` to the AccessToken project. AccessTokenClient is already standard2.0.

**Comment by ivarne** [comment]
Seems like I did not read the diff closely enough. A test project was updated to net8.0 (no multi targeting) and my comments was based on that. So sorry. This looks good.👍

**Review by acn-sbuad — APPROVED** [review]
🎈

**Comment by SandGrainOne** [comment]
@tba76 @acn-sbuad 
I need input on versioning of this. My suggestions:
AccessTokenClient -> v1.3.0
AccessToken -> 4.0.0
Both in preview.

**Pull request merged**
